"""Initial tables

Revision ID: 4a0f144e34db
Revises: 
Create Date: 2026-02-18 04:03:27.460162
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a0f144e34db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'transcriptor', 'supervisor', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('audiencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediente', sa.String(length=50), nullable=False),
    sa.Column('juzgado', sa.String(length=200), nullable=False),
    sa.Column('tipo_audiencia', sa.String(length=100), nullable=False),
    sa.Column('instancia', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('sala', sa.String(length=100), nullable=True),
    sa.Column('delito', sa.String(length=200), nullable=True),
    sa.Column('imputado_nombre', sa.String(length=200), nullable=True),
    sa.Column('agraviado_nombre', sa.String(length=200), nullable=True),
    sa.Column('especialista_causa', sa.String(length=200), nullable=True),
    sa.Column('especialista_audiencia', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'en_curso', 'transcrita', 'en_revision', 'finalizada', name='estado_audiencia'), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('deepgram_session_id', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frases_estandar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_atajo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('hablantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audiencia_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.Enum('juez', 'juez_director', 'jueces_colegiado', 'fiscal', 'defensa_imputado', 'defensa_agraviado', 'imputado', 'agraviado', 'victima', 'asesor_victimas', 'perito', 'testigo', 'asistente', 'partes_general', 'otro', name='rol_hablante'), nullable=False),
    sa.Column('etiqueta', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('auto_detectado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audiencia_id'], ['audiencias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hablantes_audiencia_id'), 'hablantes', ['audiencia_id'], unique=False)
    op.create_table('marcadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audiencia_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audiencia_id'], ['audiencias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcadores_audiencia_id'), 'marcadores', ['audiencia_id'], unique=False)
    op.create_table('segmentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audiencia_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.String(length=20), nullable=False),
    sa.Column('texto_ia', sa.Text(), nullable=False),
    sa.Column('texto_editado', sa.Text(), nullable=True),
    sa.Column('timestamp_inicio', sa.Float(), nullable=False),
    sa.Column('timestamp_fin', sa.Float(), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('es_provisional', sa.Boolean(), nullable=False),
    sa.Column('editado_por_usuario', sa.Boolean(), nullable=False),
    sa.Column('fuente', sa.Enum('streaming', 'batch', name='fuente_segmento'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('palabras_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['audiencia_id'], ['audiencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_segmentos_audiencia_id'), 'segmentos', ['audiencia_id'], unique=False)
    op.create_index(op.f('ix_segmentos_orden'), 'segmentos', ['orden'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_segmentos_orden'), table_name='segmentos')
    op.drop_index(op.f('ix_segmentos_audiencia_id'), table_name='segmentos')
    op.drop_table('segmentos')
    op.drop_index(op.f('ix_marcadores_audiencia_id'), table_name='marcadores')
    op.drop_table('marcadores')
    op.drop_index(op.f('ix_hablantes_audiencia_id'), table_name='hablantes')
    op.drop_table('hablantes')
    op.drop_table('frases_estandar')
    op.drop_table('audiencias')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
