/**
 * Corpus of common Peruvian legal terms for fuzzy matching.
 */

export const LEGAL_CORPUS = [
    "sobreseimiento",
    "acusación fiscal",
    "prisión preventiva",
    "comparecencia restringida",
    "comparecencia simple",
    "sentencia condenatoria",
    "sentencia absolutoria",
    "resolución judicial",
    "auto de enjuiciamiento",
    "auto de citación a juicio",
    "control de acusación",
    "requerimiento acusatorio",
    "requerimiento fiscal",
    "determinación de pena",
    "tipificación",
    "subsunción",
    "alegatos de apertura",
    "alegatos de clausura",
    "oralización de pruebas",
    "actuación probatoria",
    "prueba de oficio",
    "prueba anticipada",
    "delito de omisión",
    "tentativa",
    "consumación",
    "concurso real",
    "concurso ideal",
    "reparación civil",
    "pena privativa de libertad",
    "suspensión de la pena",
    "pena efectiva",
    "beneficio penitenciario",
    "terminación anticipada",
    "conclusión anticipada",
    "principio de oportunidad",
    "acuerdo reparatorio",
    "imputado",
    "agraviado",
    "actor civil",
    "tercero civil responsable",
    "fiscal provincial",
    "fiscal adjunto",
    "abogado defensor",
    "defensa técnica",
    "defensa pública",
    "procurador público",
    "testigo",
    "perito",
    "intérprete",
    "Poder Judicial",
    "Ministerio Público",
    "Corte Superior de Justicia",
    "juzgado penal unipersonal",
    "juzgado de investigación preparatoria",
    "sala penal de apelaciones",
    "INPE",
    "Policía Nacional del Perú",
    "Defensoría del Pueblo",
    "RENIEC",
    "Código Procesal Penal",
    "Código Penal",
    "artículo doscientos sesenta y ocho",
    "artículo trescientos cuarenta y nueve",
    "artículo trescientos noventa y cuatro",
    "Decreto Legislativo",
    "Ley Orgánica",
    "Acuerdo Plenario",
    "Casación",
    "jurisprudencia vinculante",
    "peligro de fuga",
    "peligro de obstaculización",
    "arraigo domiciliario",
    "arraigo familiar",
    "arraigo laboral",
    "gravedad de la pena",
    "proporcionalidad",
    "plazo razonable",
    "presunción de inocencia",
    "medida cautelar",
    "variación de medida",
    "cesación de prisión preventiva",
    "prolongación de prisión preventiva",
]
